syntax on
set number
set nomodeline
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set ignorecase
set smartcase
set incsearch
set wrap
set textwidth=80
set formatoptions=qrn1
set noerrorbells
set scrolloff=8
set showmatch
colorscheme koehler
